sudo: false
language: cpp
notifications:
  email:
    on_success: change
    on_failure: always
git:
  depth: 5
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
before_install:
  - git submodule update --init --recursive
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

  # setup newer cmake
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    else
      brew update
      brew outdated cmake || brew upgrade cmake
    fi

  - cd ${TRAVIS_BUILD_DIR}
script:
  - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON test
  - make
after_script:
  - cat compile_commands.json
