# http://www.appveyor.com/docs/appveyor-yml

notifications:
  - provider: Email
    to:
      - vik.kirilov@gmail.com
    on_build_status_changed: true
    on_build_failure: true
    on_build_success: false

clone_depth: 5
matrix:
  fast_finish: true
branches:
  except:
    - gh-pages
platform:
  - x64
configuration:
  - Debug
  - Release

install:
  - git submodule update --init --recursive

before_build:
  - cmake -G "Visual Studio 14 2015 Win64" test
build:
  parallel: true
  project: example.sln
