//
// Created by Gary on 12/3/2017.
//

#ifndef AWESOMEMEDIALIBRARYMANAGER_ABOUTBOX_H
#define AWESOMEMEDIALIBRARYMANAGER_ABOUTBOX_H


class AboutBox {

};


#endif //AWESOMEMEDIALIBRARYMANAGER_ABOUTBOX_H
