//
// Created by gary on 6/14/19.
//

#ifndef AWESOMEMEDIALIBRARYMANAGER_UNDOREDOHELPER_H
#define AWESOMEMEDIALIBRARYMANAGER_UNDOREDOHELPER_H


class UndoRedoHelper
{

};


#endif //AWESOMEMEDIALIBRARYMANAGER_UNDOREDOHELPER_H
